name: "publish"
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
  


jobs:
    create-release:
        runs-on: ubuntu-latest
        outputs:
            RELEASE_UPLOAD_ID: ${{ steps.create_release.outputs.id }}

        steps:
            - uses: actions/checkout@v2
              with:
                fetch-depth: 0
            - name: setup node
              uses: actions/setup-node@v1
              with:
                node-version: 14
            - name: get version
              run: echo "PACKAGE_VERSION=$(node -p "require('./src-tauri/tauri.conf.json').package.version")" >> $GITHUB_ENV
            - name: 'Get Previous tag'
              id: previoustag
              uses: "WyriHaximus/github-action-get-previous-tag@v1.1.0"
              with:
                fallback: 1.0.0
            - name: create release
              id: create_release
              uses: actions/create-release@v1.1.0
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: ${{ env.PACKAGE_VERSION }}
                  release_name: "Client v${{ env.PACKAGE_VERSION }}"
                  body: "**Full Changelog**: https://github.com/Thorium0/Rust-TcpChat/compare/${{ steps.previoustag.outputs.tag }}...${{ env.PACKAGE_VERSION }}"
                  draft: false
                  prerelease: false
    build-tauri:
        needs: create-release
        strategy:
            fail-fast: false
            matrix:
                platform: [macos-latest, ubuntu-latest, windows-latest]

        runs-on: ${{ matrix.platform }}
        steps:
            - uses: actions/checkout@v2
            - name: setup node
              uses: actions/setup-node@v1
              with:
                  node-version: 14
            - name: install Rust stable
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
            - name: install tauri bundler
              run: cargo install tauri-bundler --force
            - name: install webkit2gtk libgtk-3-dev libappindicator3-dev (ubuntu only)
              if: matrix.platform == 'ubuntu-latest'
              run: |
                  sudo apt-get update
                  sudo apt-get install -y webkit2gtk-4.0 libgtk-3-dev libappindicator3-dev
            - name: install app dependencies and build it
              run: yarn && yarn build
            - uses: tauri-apps/tauri-action@v0
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  releaseId: ${{ needs.create-release.outputs.RELEASE_UPLOAD_ID }}
